address = """<div class="large">Rasmus Erik &#64; solsort.dk</div>
<div>R. E. V. Jensen<br />
Frederikssundsvej 14f 4mf<br />
DK-2400 Copenhagen NV <br />
Tel.: (+45) 60 70 30 81
</div>"""

keywords = """computer scientist,
freelance consultant,
part-time developer at DBC,
mobile development,
structured data compression,
usability,
debugging,
technical talks,
discrete mathematics,
information theory,
public speaking,
educator,
data mining,
library and information science,
cryptography,
scripting language implementation,
spidermonkey, 
sambas student at RUC,
lightscript,
optimisation,
jvm bytecodes,
argentine tango,
statistics,
social singing,
project management,
documentation,
mythology,
storytelling,
INTP,
dance,
C, 
C++, 
Java, 
Standard ML, 
Scheme, 
Python, 
EcmaScript / JavaScript, 
Lua,
x86 assembler, 
Qt,
domain specific languages, 
partial evaluation,
test driven development,
runtime machine code generation and debugging, 
lecturer,
course design,
jam sessions,
qualitative research,
scrum, 
combinatorics,
constructionism,
open source,
mensa,
empty inbox,
lindy hop,
salsa,
role playing,
guitar,
piano,
ecology,
blues improvisation,
digital image editing,
dungeon master,
illusions / magic,
regular dinner parties,
3d graphics,
global brain,
photography,
psychometrics,
toastmaster,
juggling,
horseback riding,
bicycling,
frugality,
no tv,
vegetarian,
psychology,
mysticism,
massage,
non-consumerism,
interrail, 
norse myths,
mythology,
religion,
sufism,
christianity,
zen,
taoism,
el corte visitor,
couchsurfing,
poetry,
english,
danish,
basic spanish,
basic german,
synchronosity""".replace("\n", " ")
